#!/bin/csh -f
# =============================================================================
# projection_pipeline.csh
# Auto-generated by notebooks/projection_pipeline.ipynb
# Generated: 2026-07-17T17:03:38
#
# PDB ID      : 4J4X
# Assembly    : Biological Assembly (RCSB assembly CIF)
# APIX / RES  : 1.0 / 4.0
# Box size    : 192
# Gallery     : eman:delta=10.0, sym=c1
#
# Prerequisites:
#   - conda env "eman2" with EMAN2
#   - curl (for download)
#   - gemmi (for CIF→PDB if re-running model prep outside the notebook)
# =============================================================================
setenv PROJECT_ROOT /Users/ahgsur/github/structure_tools/Projection
cd $PROJECT_ROOT

# step recorded #1
conda run -n eman2 -- e2version.py

# step recorded #2
curl -fsSL https://files.rcsb.org/download/4J4X-assembly1.cif -o /Users/ahgsur/github/structure_tools/Projection/data/4J4X/raw/4J4X-assembly1.cif

# step recorded #3
# Gemmi write_pdb -> /Users/ahgsur/github/structure_tools/Projection/data/4J4X/models/4J4X_assembly1.pdb (CLI equivalent: gemmi convert /Users/ahgsur/github/structure_tools/Projection/data/4J4X/raw/4J4X-assembly1.cif /Users/ahgsur/github/structure_tools/Projection/data/4J4X/models/4J4X_assembly1.pdb)

# step recorded #4
conda run -n eman2 -- e2pdb2mrc.py /Users/ahgsur/github/structure_tools/Projection/data/4J4X/models/4J4X_assembly1.pdb /Users/ahgsur/github/structure_tools/Projection/data/4J4X/maps/4J4X_assembly1_apix1.0_res4.0_box192.mrc --apix=1.0 --res=4.0 --box=192 --het --center

# step recorded #5
conda run -n eman2 -- e2iminfo.py /Users/ahgsur/github/structure_tools/Projection/data/4J4X/maps/4J4X_assembly1_apix1.0_res4.0_box192.mrc -H

# step recorded #6
conda run -n eman2 -- e2iminfo.py /Users/ahgsur/github/structure_tools/Projection/data/4J4X/maps/4J4X_assembly1_apix1.0_res4.0_box192.mrc -s

# step recorded #7
conda run -n eman2 -- python /Users/ahgsur/github/structure_tools/Projection/data/4J4X/scripts/_inspect_mrc_header.py

# step recorded #8
conda run -n eman2 -- python /Users/ahgsur/github/structure_tools/Projection/data/4J4X/scripts/_check_com.py

# step recorded #9
conda run -n eman2 -- python /Users/ahgsur/github/structure_tools/Projection/data/4J4X/scripts/_export_volume_numpy.py

# step recorded #10
conda run -n eman2 -- e2project3d.py /Users/ahgsur/github/structure_tools/Projection/data/4J4X/maps/4J4X_assembly1_apix1.0_res4.0_box192.mrc --outfile=/Users/ahgsur/github/structure_tools/Projection/data/4J4X/projections/4J4X_proj_alt0_az0_phi0.hdf --orientgen=single:alt=0.0:az=0.0:phi=0.0 --sym=c1 --projector=standard

# step recorded #11
conda run -n eman2 -- e2project3d.py /Users/ahgsur/github/structure_tools/Projection/data/4J4X/maps/4J4X_assembly1_apix1.0_res4.0_box192.mrc --outfile=/Users/ahgsur/github/structure_tools/Projection/data/4J4X/projections/4J4X_proj_alt90_az0_phi0.hdf --orientgen=single:alt=90.0:az=0.0:phi=0.0 --sym=c1 --projector=standard

# step recorded #12
conda run -n eman2 -- e2iminfo.py /Users/ahgsur/github/structure_tools/Projection/data/4J4X/projections/4J4X_proj_alt0_az0_phi0.hdf -s

# step recorded #13
conda run -n eman2 -- e2iminfo.py /Users/ahgsur/github/structure_tools/Projection/data/4J4X/projections/4J4X_proj_alt90_az0_phi0.hdf -s

# step recorded #14
conda run -n eman2 -- e2project3d.py /Users/ahgsur/github/structure_tools/Projection/data/4J4X/maps/4J4X_assembly1_apix1.0_res4.0_box192.mrc --outfile=/Users/ahgsur/github/structure_tools/Projection/data/4J4X/projections/4J4X_gallery_eman_delta10.hdf --orientgen=eman:delta=10.0:inc_mirror=0 --sym=c1 --projector=standard

# step recorded #15
conda run -n eman2 -- e2iminfo.py /Users/ahgsur/github/structure_tools/Projection/data/4J4X/projections/4J4X_gallery_eman_delta10.hdf -c

# step recorded #16
conda run -n eman2 -- e2iminfo.py /Users/ahgsur/github/structure_tools/Projection/data/4J4X/projections/4J4X_gallery_eman_delta10.hdf -a -E

# step recorded #17
conda run -n eman2 -- e2proc2d.py /Users/ahgsur/github/structure_tools/Projection/data/4J4X/projections/4J4X_proj_alt0_az0_phi0.hdf /Users/ahgsur/github/structure_tools/Projection/data/4J4X/png/4J4X_proj_alt0_az0_phi0.png --outtype=png

# step recorded #18
conda run -n eman2 -- e2proc2d.py /Users/ahgsur/github/structure_tools/Projection/data/4J4X/projections/4J4X_proj_alt90_az0_phi0.hdf /Users/ahgsur/github/structure_tools/Projection/data/4J4X/png/4J4X_proj_alt90_az0_phi0.png --outtype=png

# step recorded #19
conda run -n eman2 -- python /Users/ahgsur/github/structure_tools/Projection/data/4J4X/scripts/_gallery_write_pngs.py

# Optional: regenerate PDB from CIF with gemmi CLI (if not using the notebook):
# gemmi convert /Users/ahgsur/github/structure_tools/Projection/data/4J4X/raw/4J4X-assembly1.cif /Users/ahgsur/github/structure_tools/Projection/data/4J4X/models/4J4X_assembly1.pdb

echo "Done. MRC: /Users/ahgsur/github/structure_tools/Projection/data/4J4X/maps/4J4X_assembly1_apix1.0_res4.0_box192.mrc"
echo "Gallery: /Users/ahgsur/github/structure_tools/Projection/data/4J4X/projections/4J4X_gallery_eman_delta10.hdf"
